[app]
  [app.server]
    host = "0.0.0.0"
    port = 8080
  [app.db]
    username = "postgres"
    password = "admin"
    host     = "db"
    dbname   = "postgres"
    port     = "5432"
    sslmode  = "disable"